### ISSUE TITLE
Remute throws an exception when object contains struct parameters / properties

### ISSUE THREAD

**Issue by michael-wolfenden** [ababik/Remute#1]
Given the following:

```csharp
public class Employee
{
	public Guid Id { get; }

	public string FirstName { get; }

	public string LastName { get; }

	public Employee(Guid id, string firstName, string lastName)
	{
		Id = id;
		FirstName = firstName;
		LastName = lastName;
	}
}
```

Calling `With`:

```csharp
var remute = new Remute.Remute();
var expected = new Employee(Guid.NewGuid(), "John", "Doe");
var actual = remute.With(expected, x => x.FirstName, "Foo");
```

Results in the following exception:

```
Expression of type 'System.Guid' cannot be used for return type 'System.Object'
at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters)
at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
at Remute.Remute.GetParameterResolvers(Type type, ConstructorInfo constructor)
at Remute.Remute.GetActivationContext(Type type)
at Remute.Remute.With[TInstance,TValue](TInstance instance, Expression`1 expression, TValue value)
at UserQuery.Main()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by ababik-frozenmountain** [comment]
Thanks @michael-wolfenden for submitting this bug. It has been fixed.
